### ISSUE TITLE
RENAME should send RPL_TOPIC, RPL_NAMREPLY and MODE to legacy clients

### ISSUE THREAD

**Issue by jesopo** [oragono/oragono#300] opened 2018-11-05 16:22 UTC
As per: https://github.com/ircv3/ircv3-specifications/blob/4084a6439f2aa85509fe2629de688c90e792af5c/extensions/rename.md#implementation-considerations

> Server implementations MUST implement a fallback method for legacy clients. This method MUST involve sending the legacy client a PART message for the old channel name, with the rename reason as the part message if given, followed by the usual messages that would be sent if the legacy client had joined the new channel normally (JOIN, RPL_TOPIC, RPL_NAMREPLY, etc) and finally a MODE message to restore any prefix modes that the legacy client has applied to it.

https://github.com/oragono/oragono/blob/a7e88f51fe12d05678574bc8bfbe53fdbee77a35/irc/handlers.go#L2004-L2016

**Comment by slingamn** [comment] 2018-11-06 05:35
Nice, thanks. This is probably what's going on in #174.

**Comment by slingamn** [comment] 2019-03-11 09:18
"finally a `MODE` message to restore any prefix modes that the legacy client has applied to it" is in tension with the guidance we implemented on #353 ("imo MODE should only be sent to update any changes since the NAMES"). That is to say, the information about the client's channel mode is present in the NAMES, same as on a regular join, so it should be redundant to send a MODE line.

**Comment by jwheare** [comment] 2019-03-11 09:26
Yeah I think the MODE is unnecessary and needs to be fixed in that spec. Will check.

**Comment by jwheare** [comment] 2019-03-11 10:09
Checked and confirmed. Left a review comment on the rename spec.

**Closed** 2019-03-11 22:41 UTC
