### ISSUE TITLE
Various issues with email verification of accounts

### ISSUE THREAD

**Issue by poVoq** [oragono/oragono#666] opened 2019-11-13 22:07 UTC
Ok so I got verification by email working it seems, but it has a lot of issues and is not working as documented or instructed by email

First of all I needed to use:
`/NS REGISTER <password> [email]` (account name is automatically taken from current nick) 
While the manual says `/NS REGISTER accountname password` (and nothing else)

Then I get an email that says:
`/MSG NickServ VERIFY accountname verificationcode`
But when I type that Nickserv complaints: `Invalid parameters. For usage, do /msg NickServ HELP REGISTER`

Only when I use: `/NS VERIFY accountname verificationcode` it seems to work.

However initially Nickserv also said `Invalid account verification code` until I realized the `accountname` seems to be case-sensitive, but in the email the `accountname` was written in all small letters.

So it seems like the email that gets send needs to be fixed and the case-sensitivity issue looked at :)

Ah I am using the latest dev docker image so 1.2rc1.

**Comment by slingamn** [comment] 2019-11-13 22:36
I can't reproduce either of these issues against [darwin.network](https://irc.darwin.network), which is running 1.2.0-rc1 approximately. Specifically, here I register an account, then verify it using a `PRIVMSG` to nickserv (instead of the `NS` command) and a lowercase version of the account name:

````
:ShivaramRegTest!~a@127.0.0.1 221 ShivaramRegTest +Z
ns register shivarampassphrase bihzad@gmail.com
:NickServ!NickServ@localhost NOTICE ShivaramRegTest :Account created, pending verification; verification code has been sent to mailto:bihzad@gmail.com
privmsg nickserv :VERIFY shivaramregtest h6nusymeu7tuetgwqdx67yid2w
:NickServ!NickServ@localhost NOTICE ShivaramRegTest :Account created
:NickServ!NickServ@localhost NOTICE ShivaramRegTest :You're now logged in as ShivaramRegTest
ns unregister shivaramregtest
:NickServ!NickServ@localhost NOTICE ShivaramRegTest :Warning: unregistering this account will remove its stored privileges.
:NickServ!NickServ@localhost NOTICE ShivaramRegTest :To confirm account unregistration, type: /NS UNREGISTER shivaramregtest 3338757023
ns unregister shivaramregtest 3338757023
:NickServ!NickServ@localhost NOTICE ShivaramRegTest :Successfully unregistered account shivaramregtest
````

Can you reproduce there and provide a transcript of the raw protocol lines?

The manual being out of date is a combination of https://github.com/oragono/oragono-site/issues/8 and the fact that 1.2.0 is still unreleased --- this should be resolved soon.

**Comment by slingamn** [comment] 2019-11-13 23:02
If it's easier for you to provide raw protocol lines from your own server, that works as well --- I wanted to eliminate the possibility of this issue being caused by an email server misconfiguration, but that seems unlikely.

**Comment by poVoq** [comment] 2019-11-14 00:00
`ns register shivarampassphrase [redacted]@gmail.com`
Is what you actually typed?
Because on my server the commands seem to be case-sensitive. So if I type in `/ns register bla bla@example.com` I get `/ns: No such command `

I have to type `/NS REGISTER bla bla@example.com`

**Comment by poVoq** [comment] 2019-11-14 00:14
Ok, so this might be a issue with different clients. In HexChat the commands work as you say and written in the email, but with the Dispatch web-irc client it only works as described above.

**Comment by slingamn** [comment] 2019-11-14 00:50
I recommend providing raw I/O logs if you can produce them. The best place to enable this is probably within Dispatch, but you can also make them on the Oragono side by temporarily enabling raw I/O logging. Set `type` to `*` here:

https://github.com/oragono/oragono/blob/cbb3fe51b9028dbc84d3ff3fd4892aac02816177/oragono.yaml#L482

and then set `level` to `debug` here:

https://github.com/oragono/oragono/blob/cbb3fe51b9028dbc84d3ff3fd4892aac02816177/oragono.yaml#L485

**Comment by slingamn** [comment] 2019-11-14 01:07
Closing this on our side for now --- feel free to reopen if you can reproduce a server-side bug.

**Closed by slingamn** 2019-11-14 01:07 UTC
