### ISSUE TITLE
/version doesn't quite work right

### ISSUE THREAD

**Issue by Nerdmaster** [oragono/oragono#296] opened 2018-10-23 15:26 UTC
Asking the server its version semi-works, but results in an error:

    oragono-0.12.0-5550396 irc.<redacted>.com
    ACCCOMMANDS=CREATE,VERIFY AWAYLEN=500 CASEMAPPING=ascii CHANMODES=beI,,lk,imntEs CHANNELLEN=64 CHANTYPES=# ELIST=U EXCEPTS= INVEX= KICKLEN=1000 MAXLIST=beI:60 MAXTARGETS=4 MODES= :are supported by this server
    * :Error assembling message for sending

I think this is related to another issue we're experiencing, where half-ops register, but don't show up for clients.

**Comment by DanielOaks** [comment] 2018-10-23 16:11
Hmm, this sounds weird. Thanks for the yell letting us know, I'll try to reproduce this on my end and see if I can see what's going on here.

**Comment by slingamn** [comment] 2018-10-23 19:56
If you enable the "internal" logging category, the log might have more information about what's going on. Here's the logging config I'm using in production:

````yaml
logging:
    -
        method: stderr
        type: localconnect localconnect-ip quit internal rehash
        level: debug
````

See if it says anything about the half-op issue as well? (I could take a look at that independently if you have repro steps.)

**Comment by Nerdmaster** [comment] 2018-10-23 20:14
Thanks, I'll set it up and let you know what I find

**Comment by slingamn** [comment] 2018-10-24 01:40
Looks like there's an edge case where one of the `RPL_ISUPPORT` parameters can be invalid (they depend on the configuration). Here are some options:

1. If you're comfortable sending me your config file, I can probably use that to reproduce the issue. (My e-mail address is on my GitHub profile page.)
1. I can also send you a patch that you could apply, which would provide more debugging information.
1. If necessary, I can probably figure out which parameter is breaking just by eyeballing the code at length.

**Comment by Nerdmaster** [comment] 2018-10-24 16:34
Okay, I've scrubbed the config file, using "xxxxxx" in a variety of sensitive locations.  I think it's safe to just put it here at this point
[ircd.zip](https://github.com/oragono/oragono/files/2511396/ircd.zip)

**Comment by slingamn** [comment] 2018-10-24 18:43
Does your actual network name have a space or a colon in it?

**Comment by Nerdmaster** [comment] 2018-10-24 18:54
Oh... yes, it does.  I didn't realize that would cause problems.  I changed
it and all's well.

**Comment by slingamn** [comment] 2018-10-24 19:18
In future, we'll either make this an explicit error, or we'll add escaping for special characters (there is a spec for it but we're not sure how widely implemented it is).

**Comment by slingamn** [comment] 2018-10-24 20:20
Closing in favor of #297.

**Closed by slingamn** 2018-10-24 20:20 UTC
