### ISSUE TITLE
Error when Nickname mixed Arabic and English

### ISSUE THREAD

**Issue by zaher** [oragono/oragono#273] opened 2018-06-03 21:41 UTC
I got error "Erroneous nickname" when set my nickname to this or even with number instead of English latter:
مjم

**Comment by DanielOaks** [comment] 2018-06-03 22:08
Hey Zaher! Unfortunately this is restrictions put in place by the Unicode people – specifically, the ones that made [PRECIS](https://tools.ietf.org/html/rfc7790) and the UsernameCaseMapped profile. I suspect mixing scripts in that way is specifically disallowed by them. In addition, the restriction of IRC that the first character of a nickname can't be a number.

Because of that, I'm not really able to change it unfortunately 😅

**Comment by zaher** [comment] 2018-06-03 22:40
No problem with numbers, 
The weird thing that Oragono accepts unicode name like زاهر but if added one English latter it refuses it.

BTW I modified my client to use only English nickname.

**Comment by slingamn** [comment] 2018-06-03 22:48
Related discussions: #137 (directly relevant as it was a case where we were thinking about relaxing the PRECIS constraints), #178.

**Comment by DanielOaks** [comment] 2018-06-03 23:34
Ah yeah, the issue is that PRECIS specifically forbids things with BIDI markers in it iirc, which means that certain scripts (Japanese, Arabic, etc) might not work with others. Specifically, scripts written right-to-left and those written left-to-write may not work together – because of how those RTL and LTR languages work in Unicode, the extra characters can mess up and make the same visual letters look different in code.

**Comment by DanielOaks** [comment] 2018-07-02 06:04
Yeah I'm going to close this for now, since it's a dependency on the underlying PRECIS system unfortunately we can't solve this ourselves.

**Closed by DanielOaks** 2018-07-02 06:04 UTC
